version: '3.8'

services:
  reproduce.py:
    image: anonymoussubmission4/lyapunovagent:latest
    build: .
    depends_on:
      - mlflow
    volumes:
      - ./srccode_data:/srccode/presets/srccode_data
    entrypoint:
      - python 
      - -u 
      - reproduce.py
    

  mlflow:
    image: anonymoussubmission4/lyapunovagent:latest
    build: .
    ports:
      - ${MLFLOW_PORT:-5000}:5000
    volumes:
      - ./srccode_data:/srccode/presets/srccode_data
    entrypoint: 
      - python 
      - -m 
      - mlflow 
      - server
      - --host=0.0.0.0
      - --port=5000
      - --backend-store-uri=file:///srccode/presets/srccode_data/mlruns

